server:
  port: 8081
spring:
  mvc:
    #fuck, this file don't support Chinese character.
    #do not stop 404 error,let's handle by ourselves error message.
    throw-exception-if-no-handler-found: true
  resources:
    #do not build map this project.because we implement ourselves unify error message.
    add-mappings: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/springbootdemo?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource



