server:
  port: 8081
spring:
  mvc:
    #fuck, this file don't support Chinese character.
    #do not stop 404 error,let's handle by ourselves error message.
    throw-exception-if-no-handler-found: true
  resources:
    #do not build map this project.because we implement ourselves unify error message.
    add-mappings: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/springbootdemo?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.160.128
    port: 6379
    timeout: 500
    password: 123456
    lettuce:
      shutdown-timeout: 100ms
      pool:
        min-idle : 5
        max-idle : 10
        max-active : 8
        max-wait : 1ms