server:
  port: 8081
spring:
  mvc:
    #当出现 404 错误时, 直接抛出异常.
    throw-exception-if-no-handler-found: true
  resources:
    #不要为我们工程中的资源文件建立映射.
    add-mappings: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/springbootdemo?useSSL=false&characterEncoding=utf8&serverTimezone=GMT
    type: com.alibaba.druid.pool.DruidDataSource